import 'server-only';
import { createClient } from '@/lib/supabase/server';
import { generateStarterRider, type GeneratedRider } from './generate';

/**
 * Server-side rider persistence. Everything here runs with the logged-in
 * player's session, so RLS guarantees a player only ever touches their own row.
 */

export interface StoredRider extends GeneratedRider {
  id: string;
  /** True for AI/test fillers generated by the Rookie AI Generator V1 (no player_id). */
  isAi: boolean;
  /**
   * A snapshot of `condition` as it was immediately before the most recent
   * write — the only thing that lets the UI show a real up/down/flat trend
   * instead of guessing. Equal to `condition` until the first processed
   * training (see lib/training/engine.ts), so a fresh rider reads as flat.
   */
  conditionPrevious: StoredRider['condition'];
}

function fromRow(row: Record<string, unknown>): StoredRider {
  return {
    id: row.id as string,
    firstName: row.first_name as string,
    surname: row.surname as string,
    countryName: row.country_name as string,
    countryIso2: row.country_iso2 as string,
    age: row.age as number,
    attributes: row.attributes as StoredRider['attributes'],
    condition: row.condition as StoredRider['condition'],
    conditionPrevious: (row.condition_previous as StoredRider['condition']) ?? (row.condition as StoredRider['condition']),
    inferredArchetype: row.inferred_archetype as string,
    potential: row.potential as number,
    trainability: row.trainability as number,
    professionalism: row.professionalism as number,
    recovery: row.recovery as number,
    generatorVersion: row.generator_version as string,
    isAi: Boolean(row.is_ai),
  };
}

/** The current player's rider, or null if they have none yet. */
export async function getMyRider(): Promise<StoredRider | null> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data, error } = await supabase
    .from('riders')
    .select('*')
    .eq('player_id', user.id)
    .maybeSingle();

  if (error || !data) return null;
  return fromRow(data);
}

/**
 * Ensure the current player has exactly one starter rider.
 *
 * Idempotent by design: if a rider already exists it is returned untouched and
 * NOTHING is regenerated. Only a brand-new player triggers generation. The
 * UNIQUE(player_id) constraint is the final backstop against a race between two
 * simultaneous requests — the loser's insert fails and we re-read the winner's
 * row.
 */
export async function ensureStarterRider(): Promise<StoredRider | null> {
  const existing = await getMyRider();
  if (existing) return existing;

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const rider = generateStarterRider(Math.random);

  const { data, error } = await supabase
    .from('riders')
    .insert({
      player_id: user.id,
      first_name: rider.firstName,
      surname: rider.surname,
      country_name: rider.countryName,
      country_iso2: rider.countryIso2,
      age: rider.age,
      attributes: rider.attributes,
      condition: rider.condition,
      condition_previous: rider.condition,
      inferred_archetype: rider.inferredArchetype,
      potential: rider.potential,
      trainability: rider.trainability,
      professionalism: rider.professionalism,
      recovery: rider.recovery,
      generator_version: rider.generatorVersion,
    })
    .select('*')
    .single();

  // A concurrent request won the race and inserted first: re-read that row.
  if (error) return getMyRider();

  // Bike Condition V1 (see lib/facilities/bike.ts) starts every new rider at
  // a full 100/100/100 — best-effort: a failure here must not fail rider
  // creation itself, since getMyBikeCondition() already falls back to a
  // full-condition default when no row exists yet.
  await supabase.from('bike_condition').insert({ rider_id: data.id });

  return fromRow(data);
}

/**
 * Every rider currently in the game — the real player(s) and any AI fillers.
 * Used by the admin/test peloton view only; not part of any player-facing page.
 */
export async function listAllRiders(): Promise<StoredRider[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('riders')
    .select('*')
    .order('is_ai', { ascending: true })
    .order('created_at', { ascending: true });

  if (error || !data) return [];
  return data.map(fromRow);
}

/**
 * Persists the condition cost of a processed training run. Called only by
 * the training engine (lib/training/engine.ts) after its loop over all
 * pending plans finishes.
 *
 * Training Progress Accumulator V1 (see the chat report): this used to
 * also write `attributes` in one batched call at the end of the loop.
 * Attribute gains are now written per-plan, atomically, inside
 * process_training_plan() (supabase/schema.sql) — so this function must
 * NEVER touch `attributes` anymore; doing so would risk overwriting a
 * concurrent run's already-persisted gain with a stale local snapshot.
 *
 * `previousCondition` is the rider's condition as it was *before* this
 * change — written to condition_previous so the Stav jazdca UI can compute
 * a real trend arrow later, never inferred from "something happened recently".
 */
export async function applyConditionResult(
  riderId: string,
  condition: Record<'energy' | 'fatigue' | 'form' | 'fitness' | 'morale', number>,
  previousCondition: Record<'energy' | 'fatigue' | 'form' | 'fitness' | 'morale', number>,
): Promise<void> {
  const supabase = await createClient();
  await supabase
    .from('riders')
    .update({ condition, condition_previous: previousCondition })
    .eq('id', riderId);
}
